services:
  db:
    image: postgres:16-alpine
    container_name: hhm-shop-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-hhm_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-hhm_password}
      POSTGRES_DB: ${DB_NAME:-hhm_shop_lms}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hhm-shop-web
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/public/uploads
    environment:
      - DATABASE_URL=postgres://${DB_USER:-hhm_user}:${DB_PASSWORD:-hhm_password}@db:5432/${DB_NAME:-hhm_shop_lms}
      - NEXT_PUBLIC_APP_URL=http://185.208.227.129:3000
    depends_on:
      - db

volumes:
  postgres_data:
