
import { Language } from "@/modules/shared/lib/i18n-constants";

export const PRODUCT_DETAIL_DICT: Record<Language, Record<string, string>> = {
  hu: {
    backToProducts: "Vissza a termékekhez",
    features: "Jellemzők",
    dimensions: "Méretek és Súly",
    noSpecs: "Nincsenek specifikációk rögzítve.",
    weight: "Súly",
    dimensionsLabel: "Méretek (Szé x Ma x Mé)",
    noDimensions: "Nincsenek méretek megadva ehhez a variációhoz.",
    detailedDescription: "Részletes leírás",
    noDescription: "Nincs elérhető leírás ehhez a termékhez.",
    premiumQuality: "Prémium Minőség",
    original: "Eredeti",
    featuredOffer: "Kiemelt Ajánlat",
    productLine: "Termékcsalád",
    skuPrefix: "Cikkszám",
    priceNotAvailable: "Ár nem elérhető",
    addToCart: "Kosárba rakom",
    listenAudio: "Hangminta hallgatása",
    otherFamilyMembers: "A család további tagjai",
    currentProduct: "Jelenlegi",
    variants: "Méretek / Variációk",
    noImage: "Nincs kép",
    item: "termék",
    variation: "Variáció",
    showMore: "Mutass többet",
    unnamedProduct: "Névtelen termék"
  },
  en: {
    backToProducts: "Back to products",
    features: "Features",
    dimensions: "Dimensions and Weight",
    noSpecs: "No specifications recorded.",
    weight: "Weight",
    dimensionsLabel: "Dimensions (W x H x D)",
    noDimensions: "No dimensions specified for this variant.",
    detailedDescription: "Detailed description",
    noDescription: "No description available for this product.",
    premiumQuality: "Premium Quality",
    original: "Original",
    featuredOffer: "Featured Offer",
    productLine: "Product Line",
    skuPrefix: "SKU",
    priceNotAvailable: "Price not available",
    addToCart: "Add to cart",
    listenAudio: "Listen to sample",
    otherFamilyMembers: "Other members of the family",
    currentProduct: "Current",
    variants: "Sizes / Variations",
    noImage: "No image",
    item: "item",
    variation: "Variation",
    showMore: "Show more",
    unnamedProduct: "Unnamed product"
  },
  sk: {
    backToProducts: "Späť na produkty",
    features: "Vlastnosti",
    dimensions: "Rozmery a hmotnosť",
    noSpecs: "Žiadne špecifikácie nie sú zaznamenané.",
    weight: "Hmotnosť",
    dimensionsLabel: "Rozmery (Š x V x H)",
    noDimensions: "Pre tento variant nie sú zadané žiadne rozmery.",
    detailedDescription: "Podrobný popis",
    noDescription: "Pre tento produkt nie je k dispozícii žiadny popis.",
    premiumQuality: "Prémiová kvalita",
    original: "Originál",
    featuredOffer: "Špeciálna ponuka",
    productLine: "Produktový rad",
    skuPrefix: "Kód",
    priceNotAvailable: "Cena nie je k dispozícii",
    addToCart: "Vložiť do košíka",
    listenAudio: "Vypočuť si ukážku",
    otherFamilyMembers: "Ďalší členovia rodiny",
    currentProduct: "Aktuálny",
    variants: "Veľkosti / Varianty",
    noImage: "Žiadny obrázok",
    item: "položka",
    variation: "Variant",
    showMore: "Zobraziť viac",
    unnamedProduct: "Nepomenovaný produkt"
  }
};
